### PR TITLE
729 flaticon css

### PR DESCRIPTION
**Pull request by janette**
**Issue and Acceptance Criteria**

https://github.com/NuCivic/dkan/issues/729

### CODE REVIEW

**Comment by janette** [comment]
This should only have one commit, ~~do not merge~~.

Ready to merge

**Comment by nucivicmachine** [comment]
QA site created: http://729-flaticon-css.dkan_dataset.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://729-flaticon-css.dkan_dataset.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://729-flaticon-css.dkan_dataset.qa.nuamsdev.com

**Pull request merged**
