### PR TITLE
Allow state select leaftlet

### PR DESCRIPTION
**Pull request by jacintocapote**
ref: NuCivic/internal#865

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://allow_state_select_leaftlet.dkan_dataset.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://allow_state_select_leaftlet.dkan_dataset.qa.nuamsdev.com

**Comment by janette** [comment]
@jacintocapote  which should we use? #141 or this?

allow_state_select_leaftlet_by_jacintocapote_ _pull_request__148_ _nucivic_dkan_dataset_and_validate_json_input_leaflet_draw_widget_by_jacintocapote_ _pull_request__141_ _nucivic_dkan_dataset

**Comment by dafeder** [comment]
@janette these are two different issues, both should be brought in eventually

**Comment by janette** [comment]
@dafeder ok this commit has them both: 860437c9e6813cf829fee91b31b0968a2f4c5d7a
should we create a 7.x-1.x tag?

**Comment by jacintocapote** [comment]
@janette we can remove the revision. These was If I remember well because I add the utility but we continue working adding new functionality, ..... and I need the specific version for a project

**Comment by janette** [comment]
Updates added to the consolidation branch: https://github.com/NuCivic/dkan/pull/1387/commits/66c753fdb56126d0ac91b14ac0cd1cb5f655bcc2

**Pull request closed without merging**
