### PR TITLE
NuCivic/dkan#672 Add bootstrap group-list classes and update css for resource list on resource node view

### PR DESCRIPTION
**Pull request by janette**

### CODE REVIEW

**Comment by janette** [comment]
### Issue: https://github.com/NuCivic/dkan/issues/672

### QA site

 http://672-theme-resource-list-qa.dkan.qa.nuamsdev.com/dataset/wisconsin-polling-places/resource/bdc20821-8727-42e4-8a90-0ad38da315c5

### Acceptance test
- [ ] the resource list on the resource page should be styled as a bootstrap group list not a bulleted list
- [ ] The active resource should be styled as such

screenshot_9_8_15__8_51_pm

**Comment by nucivicmachine** [comment]
QA site created: http://672-theme-resource-list.dkan_dataset.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://672-theme-resource-list.dkan_dataset.qa.nuamsdev.com

**Comment by nucivicmachine** [comment]
QA site created: http://672-theme-resource-list.dkan_dataset.qa.nuamsdev.com

**Pull request closed without merging**
