### PR TITLE
Fix: nuams/dkan#118

### PR DESCRIPTION
**Pull request by Akiracr**
github: nuams/dkan#118

This change is based, according to the documentation forms: https://api.drupal.org/api/drupal/developer!topics!forms_api_reference.html/7#action

This change allows drag the token language in the url i18n sites.

### CODE REVIEW

**Comment by teosibileau** [comment]
@Akiracr please see the instructions i left on #28 to get tests running for pull requests

**Comment by teosibileau** [comment]
@Akiracr this got in with #21 . I pull that one because it has some extra logic in place here -> https://github.com/nuams/dkan_dataset/pull/21/files#diff-06d8398883472fca0a571591d9830f52R241 -> that i think it's worth having

Let me know if that one works for you. If not, please feel free to re submit this in a way that works for you.

**Comment by teosibileau** [comment]
If the code in the other pull request work for you, please close this one.

**Comment by Akiracr** [comment]
Is perfect.

Thanks

**Pull request closed without merging**
