### PR TITLE
Added hability to disable sticky and promoted page

### PR DESCRIPTION
**Pull request by jacintocapote**
Added hability to disable sticky and promote to forntpage.You can add to admin/dkan/dataset_forms and disable the checkbox and then you can't see on node creation/edit.

### CODE REVIEW

**Comment by nucivicmachine** [comment]
QA site created: http://add_hability_disable_sticky_promote_front_page.dkan_dataset.qa.nuamsdev.com

**Comment by dafeder** [comment]
Discussing whether to include this in the product...

**Comment by dafeder** [comment]
This needs tests to merge. Punting for now.

**Comment by topicus** [comment]
This PR was replaced by this one to fix merge conflicts https://github.com/NuCivic/dkan_dataset/pull/197

**Pull request closed without merging**
