### PR TITLE
fix node/add/dataset using url()

### PR DESCRIPTION
**Pull request by paolomainardi**

### CODE REVIEW

**Comment by paolomainardi** [comment]
Last commit fix "node/add/resource" absolute urls.

**Comment by teosibileau** [comment]
@paolomainardi please see #22 

The same deal goes with this one! If you get this pull-request updated i'm going to get this in today!

**Comment by paolomainardi** [comment]
Rebased

**Comment by teosibileau** [comment]
this is in. Thank you very much.

**Pull request merged**
