### PR TITLE
Limit table row length

### PR DESCRIPTION
**Pull request by acouch**
See: https://github.com/NuCivic/dkan/pull/645

### CODE REVIEW

**Comment by dafeder** [comment]
Although it doesn't matter so much on something like this example, I think the "hide" overlapping the last line will be unwanted behavior on a field that has human-readable text:

screen shot 2015-08-18 at 10 42 58 am

**Comment by acouch** [comment]
Fixed that and made the row update its own function screen shot 2015-08-23 at 7 35 54 am

**Comment by nucivicmachine** [comment]
QA site created: http://limit_table_row_length.dkan_dataset.qa.nuamsdev.com

**Comment by dafeder** [comment]
I'm not seeing this functionality at all now:

http://limit_table_row_length.dkan_dataset.qa.nuamsdev.com/dataset/wisconsin-polling-places

**Comment by achraf-jeday** [comment]
@dafeder I have tested this PR and it seems to work perfectly.

Actually, you can not see this functionality because of a build issue.

You can make the following changes to drupal-org.make file: 

```
-projects[dkan_dataset][download][branch] = 7.x-1.x
+projects[dkan_dataset][download][branch] = limit_table_row_length

-includes[dkan_dataset_make] = https://raw.githubusercontent.com/NuCivic/dkan_dataset/7.x-1.x/dkan_dataset.make
+includes[dkan_dataset_make] = https://raw.githubusercontent.com/NuCivic/dkan_dataset/limit_table_row_length/dkan_dataset.make
```

Then rebuild and test the project to see it working.

**Comment by nucivicmachine** [comment]
QA site created: http://limit_table_row_length.dkan_dataset.qa.nuamsdev.com

**Pull request merged**
